baseURL = "https://ProgramProperly.com/"
languageCode = "en-us"
title = "Program Properly"
theme = "hugo-casper3"
googleAnalytics = "UA-160612490-1"

[params]
    description = "Learning to do things right"
    mainSections = ["posts"]

